### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by BarisKabdagli** [katalash/DSMapStudio#23]
DSMapStudio crashes on start without any error messages. I'm new to modding and I don't really know what the problem may be.

**Comment by SyllabusGames** [comment]
Assuming you have installed Visual C++ Redistributable x64, this is never going to get fixed with the info you have provided.
Do you have Visual Studio? (The version Unity downloads will work) If you do, you can:
-download the source code and unzip it
-double click DSMapStudio.sln (which should open Visual Studio)
-click the drop down arrow next to the green play arrow on the top bar and select DSMapStudio (this may not be necessary)
-click the green play arrow
If it doesn't compile, we need whatever text is logged in the Output window which should appear at the bottom of the screen.
If the program compiles and crashes, VS should pop up with a line highlighted. We need the file name, line number, and what error you are getting.

**Comment by BarisKabdagli** [comment]
It turned out I didn't have the Microsoft .Net Core 3.1 Desktop Runtime. It works fine now. Thanks for the help.
