### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by DSRLIN** [katalash/DSMapStudio#26]
I've downloaded the source code and have compiled it on Visual Studio 2019.
The program crashes on \Veldrid\Vk\VkGraphicsDevice.cs, line 625.
It seems that the program failed at vkEnumeratePhysicalDevices() on line 635.
The full message is:
Veldrid.VeldridException:“A Vulkan validation error was encountered: [ErrorEXT] (InstanceEXT) setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.”
My graphics card is a RTX 3060 laptop if it could help with something.

**Comment by SyllabusGames** [comment]
Do any Vulkan programs work on your laptop? Sorry if you’ve already tried this, but it looks like the default drivers for the RTX 3060 don’t support Vulkan, and you will need to download better ones from nvidia. Though it isn't exactly your hardware, this is the page everyone keeps pointing me to: https://nvidia.custhelp.com/app/answers/detail/a_id/5182
I don't have access to any remotely similar hardware, so all I can really do is research.

**Comment by DSRLIN** [comment]
It seems that it is because of my AMD intergrated graphics card caused this problem.
I've disabled it in bios and made the 3060 directly connected to the monitor.
Problem solved.

**Comment by amineyarman** [comment]
Thanks @DSRLIN. Your answer is actually correct. All I did though to fix the issue was to go to NVIDIA Control Panel.
The app was, by default using the integrated graphics card (Intel in my case). All I did was to set it up  to High-performance NVIDIA processor.
![image](https://user-images.githubusercontent.com/7825144/148997315-e554c8dc-1f67-4f67-9c14-c6cb454c3bbd.png)
