### ISSUE TITLE
Latest release doesn't render on my setup

### ISSUE THREAD

**Issue by TheStolenBattenberg** [katalash/DSMapStudio#8]
I'm running a Ryzen 1700x and GTX 1070, 16GB ram. According to what I've researched this should support Vulkan... Despite this, I'm not getting anything rendering inside the editor, but I am using the previous release before you migrated to Vulkan.

FYI on another issue, I'm trying to edit map files with a mod installed, the one that returns the original entrance from Firelink shrine to the lower Undead Burg, but saving the map causes all the objects to be removed from the map... Then reopening the map crashes the program. Any idea why this might be happening?

**Comment by katalash** [comment]
Hi, can you tell me which version you are using? The latest versions are published on the modding discord, but I haven't kept GitHub mirrors as up to date as I should.

The 1070 should definitely work, as that's the card I develop on. Make sure you have your drivers up to date though.

**Comment by TheStolenBattenberg** [comment]
Alpha 11 is the one that bugs out for me with rendering. Alpha 9 is the last one that works fine for me.

**Comment by katalash** [comment]
Ah, as I said the Github releases are out of date, and alpha 11 was known to have renderer issues that have been since fixed. I published the latest release here and will try to keep it more up to date in the future, but I tend to post my latest releases on the souls modding discord. If you haven't joined yet the invite can be found here:

https://discord.gg/mT2JJjx

It's recommended to join because that's where I typically hang out to answer questions.

**Comment by TheStolenBattenberg** [comment]
I'll keep that in mind, thanks!
